version: "3.9"
services:
  app_fila_ordem_servico:
    image: fmba-backend/fila-ordem-servico:1.0
    container_name: app_fila_ordem_servico
    restart: on-failure    
    build:      
      dockerfile: Dockerfile
      context: .
    ports:
      - "8087:8080"   
    networks:
      - fmba-bridge

networks:
  fmba-bridge:
    driver: bridge